### ISSUE TITLE
关于通道

### ISSUE THREAD

**Issue by XUPTSunHui** [yakumioto/hlf-deploy#3]
赞，这个工具不错！如果可以的话，希望能添加动态创建通道的功能

**Comment by yakumioto** [comment]
添加 channel 有的,  **createChannel** 就是, 需要提供一个 `channel.tx` 的文件

```bash
# 栗子
hlf-deploy createChannel --configFile config.yaml \
        --channelTxFile channel-artifacts/channel.tx \
        --channelName mychannel \
        --ordererOrgName OrdererOrg \
        Org1 Org2
```

**Comment by XUPTSunHui** [comment]
抱歉，没注意。后期可以加一些节点运行状态监控的功能

**Comment by yakumioto** [comment]
嗯, 除非把这个做成个服务, cli 里面加这个就有点奇怪的感觉. 哈哈哈

**Comment by XUPTSunHui** [comment]
其实不奇怪，可以在细分出一个运维版工具，给fabric运维人员用，哈哈

**Comment by yakumioto** [comment]
哈哈哈, 这个工具算是验证一些自己的想法把, 打算做个类似 https://github.com/hyperledger/cello 的工具
